final List<Map<String, dynamic>> tutors = [
  {
    "id": 1,
    "imageUrl": "assets/images/boy1.png",
    "name": "Mr. Ali Khan",
    "subject": "Mathematics",
    "charges": "1500 Rs",
    "experience": '10 Years Experience',
    "rating": "4.8",
    "detail": "10 years experience in teaching O/A Level Maths.",
    "courses": ["Algebra", "Calculus", "Geometry"],
    "availableDays": ["Mon", "Wed", "Fri", "Sat"],
  },
  {
    "id": 2,
    "imageUrl": "assets/images/girl.png",
    "name": "Ms. Sara Iqbal",
    "subject": "English Literature",
    "charges": "1200 Rs",
    "experience": "7 Years Experience",
    "rating": "4.6",
    "detail": "Expert in grammar, essay writing and literature analysis.",
    "courses": ["Essay Writing", "Poetry Analysis", "Grammar Mastery"],
    "availableDays": ["Tue", "Thu"],
  },
  {
    "id": 3,
    "imageUrl": "assets/images/boy2.png",
    "name": "Dr. Hamza Rehman",
    "subject": "Physics",
    "charges": "1800 Rs",
    "experience": "12 Years Experience",
    "rating": "4.9",
    "detail":
        "PhD in Physics. Experienced in O/A Levels, SAT Physics, and college prep.",
    "courses": ["Mechanics", "Electromagnetism", "Quantum Physics"],
    "availableDays": ["Mon", "Thu"],
  },
  {
    "id": 4,
    "imageUrl": "assets/images/girl.png",
    "name": "Ms. Amna Sheikh",
    "subject": "Biology",
    "charges": "1400 Rs",
    "experience": "6 Years Experience",
    "rating": "4.5",
    "detail":
        "Helping students understand life sciences with visuals and activities.",
    "courses": ["Human Anatomy", "Ecology", "Cell Biology"],
    "availableDays": ["Wed", "Fri", "Sun"],
  },
  {
    "id": 5,
    "imageUrl": "assets/images/boy1.png",
    "name": "Sir Usman Tariq",
    "subject": "Computer Science",
    "charges": "1600 Rs",
    "experience": "8 Years Experience",
    "rating": "4.7",

    "detail":
        "Software Engineer & Certified CS tutor for O/A Levels and IGCSE.",
    "courses": ["Python Programming", "Data Structures", "OOP"],
    "availableDays": ["Tue", "Thu", "Sat"],
  },
  {
    "id": 6,
    "imageUrl": "assets/images/girl.png",
    "name": "Mrs. Hina Aslam",
    "subject": "Chemistry",
    "charges": "1500 Rs",
    "experience": "8 Years Experience",
    "rating": "4.4",
    "detail": "MSc Chemistry with 8 years of teaching experience.",
    "courses": [
      "Organic Chemistry",
      "Inorganic Chemistry",
      "Physical Chemistry",
    ],
    "availableDays": ["Mon", "Wed", "Fri", "Sat", "Sun"],
  },
];
